version: "3"

services:
  recipe-api:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=recipe-api-db
      - DB_USER=usr_api
      - DB_PASS=brabus$01
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/dat    
    environment:
      - POSTGRES_DB=recipe-api-db
      - POSTGRES_USER=usr_api
      - POSTGRES_PASSWORD=brabus$01
volumes:
  dev-db-data: